### PR TITLE
DDF-1291 Updating Sources Tab to Display and Correctly Handle Configurables with Cardinality > 0

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- The parameters configurable is no longer filtered out from the displayed configurables.
 - Added a rebind method and updated the areas that were binding with the model to use it.  It correctly handles the binding, excluding configurables with cardinality > 0.
 - Updated how the ConfigurationCollection is initialized so that the correct service and configuration are passed in.
 - Added a 'beforeSave' trigger to the submitData function, so that configurables with cardinality > 0 can properly update themselves before the save occurs.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/102)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@brianfelix as hero, @stustison

**Comment by andrew-fiedler** [comment]
@SmithJosh as substitute hero

**Comment by SmithJosh** [comment]
Fully built and tested. Verified that the sources tab now displays the same OpenSearch query parameters as the configuration tab and felix web console, so the ticket goals were achieved. :+1: 

One comment, though: the spacing on the list of query parameters looks a bit tight compared to the configuration tab. Is this something we care about?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/102)

**Comment by andrew-fiedler** [comment]
We care about it, but it's part of a separate ticket.

**Comment by SmithJosh** [comment]
Alright, then everything looks good for this ticket

**Pull request merged**
