### PR TITLE
DDF-1264 added index for case sensitive wildcard searches

### PR DESCRIPTION
**Pull request by wmcnalli**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/108)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1: 

I might as well champion these PRs since I fell down on the job the *last* time I did.

**Comment by wmcnalli** [comment]
@coyotesqrl - thanks!

**Comment by kcwire** [comment]
+1

**Comment by pklinef** [comment]
:+1:

**Comment by emanns95** [comment]
+1

**Comment by coyotesqrl** [comment]
I've  successfully built and run itests with these two PRs.

**Pull request merged**
