### PR TITLE
DDF-1312 Prototype of XML transformers using new Parser bundle.

### PR DESCRIPTION
**Pull request by coyotesqrl**
This is the catalog PR to demonstrate the Parser prototype in this [Platform PR](https://github.com/codice/ddf-platform/pull/73).

I'm comfortable with the changes and would like us to consider whether to merge them in as an improvement. Platform needs Javadocs, but otherwise I think this is relatively clean.

@menousek 
@pklinef 
@kcwire 
@lessarderic 
@stustison 
@brendan-hofmann

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/114)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

<sup>**[transformer/catalog-transformer-xml/pom.xml, line 45 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/114#-Ju7FGVjUZQnRu8IqA4W)** ([raw file](https://github.com/codice/ddf-catalog/blob/4684196cfbc8c129d0d71250a0c4dce4a748d636/transformer/catalog-transformer-xml/pom.xml#L45)):</sup>
So can the jaxb dependencies/imports be removed now?

---

<sup>**[transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/114#-Ju7GJztYCyonas7U9Hs)** ([raw file](https://github.com/codice/ddf-catalog/blob/4684196cfbc8c129d0d71250a0c4dce4a748d636/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java#L41)):</sup>
I wonder if the Paraser stuff should just take a list of classes instead, reduce how much clients need to know/do in order to use it? Would reduce the overall amount of code as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/114)

**Comment by kcwire** [comment]
:+1: 
I think it would be good to write another ticket to refactor other places in the code where we are using JAXB.

---

Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/114)

**Comment by coyotesqrl** [comment]
If we actually merge this stuff in, I'll do exactly that. :)

---

Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

<sup>**[transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/114#-Ju7GJztYCyonas7U9Hs)** ([raw file](https://github.com/codice/ddf-catalog/blob/4684196cfbc8c129d0d71250a0c4dce4a748d636/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java#L41)):</sup>
Hmm. My only reluctance with doing that stems from knowing that `JAXBContext.newInstance()` is overloaded and can take the colon-joined path that I'm constructing in ddf-platform or a `Class[]` where the classes provided are specifically those to be bound. If we ever wanted to support that other signature, making the change you've suggested would get in the way.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/114)

**Comment by brendan-hofmann** [comment]
Reviewed 1 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

<sup>**[transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/114#-Ju7GJztYCyonas7U9Hs)** ([raw file](https://github.com/codice/ddf-catalog/blob/4684196cfbc8c129d0d71250a0c4dce4a748d636/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/AbstractXmlTransformer.java#L41)):</sup>
Well, you'd end up with a couple different configureParser() implementations, or a control variable to switch between the two behaviors. Either way is a little bit ugly, I was just thinking in terms of reducing verbosity at the client level.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/114)

**Comment by kcwire** [comment]
so what's it going to take to merge this?

**Comment by coyotesqrl** [comment]
@kcwire It's just going to take a man of vision, will, and action.

**Pull request merged**
