### PR TITLE
Ddf 1186

### PR DESCRIPTION
**Pull request by brendan-hofmann**
Move schematron stacktraces to debug.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/81)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
@stustison, can you take a look at this?

---

Review status: 0 of 1 files reviewed, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/81)

**Comment by stustison** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks broke.

---

<sup>**[schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java, line 7 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/81#-JpmBVpC2M61rA2j5pSB)** ([raw file](https://github.com/codice/ddf-catalog/blob/b24dc592240725069582bb7f769c061228a98f1e/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java#L7)):</sup>
I don't think this will actually pass our checkstyle rules.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/81)

**Comment by brendan-hofmann** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java, line 7 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/81#-JpmBVpC2M61rA2j5pSB)** ([raw file](https://github.com/codice/ddf-catalog/blob/b24dc592240725069582bb7f769c061228a98f1e/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java#L7)):</sup>
Ack, yeah. Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/81)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks broke.
Reviewed files:
- schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/81)

**Comment by shaundmorris** [comment]
@jlcsmith can you please verify this one?

**Comment by jlcsmith** [comment]
Looks good to merge.

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/81)

**Pull request merged**
