### PR TITLE
Ddf 1025

### PR DESCRIPTION
**Pull request by ricklarsen**
Initial version of in-code documentation.

### CODE REVIEW

**Comment by pklinef** [comment]
Can you remove DDF from the doc file names?  Seems unnecessary to me (also a pain if we rename the project).

**Comment by shaundmorris** [comment]
@ricklarsen it looks like builds (Travis, Jenkins, etc) may fail if they do not have graphviz installed. Curious if you have any ideas on how to handle that. Maybe @pklinef  does as well.

**Comment by ricklarsen** [comment]
That's a good point, @shaundmorris, I will have to find a way to handle that. Thanks

**Comment by shaundmorris** [comment]
We have successfully resolved all build concerns.

**Comment by mrmateo** [comment]
OK, I still had some questions on the jira ticket I was waiting to hear back on.

**Comment by mrmateo** [comment]
Also -- maybe I just missed where someone said this, but is there a way to view the documentation without having to download the source code and build it?

**Comment by shaundmorris** [comment]
It renders pretty well in Github: https://github.com/codice/ddf-catalog/blob/master/docs/src/main/doc/ExtendingCatalog.adoc. However, I'm still hoping we can still do things like search the docs after we start hosting it elsewhere.

**Comment by kcwire** [comment]
@mrmateo - We are investigating where we can host these docs and have the snapshot builds update them nightly. If you have any recommendations, I'd be glad to hear them :).

**Comment by mrmateo** [comment]
OK, thanks. Could you guys put your thoughts of where this is going somewhere public (i.e. what the end-goal is and maybe a timeline)? I've only seen descriptions of research so far and asking questions on JIRA/GitHub seems to be like pulling teeth :)

I'm mainly wanting this because confluence was made read-only which locked out people from putting changes / making updates.

**Comment by kcwire** [comment]
Sure - I'm thinking we should be able to host the docs on tools.codice.org. It also runs our nightly Jenkins jobs so it should be easy to transfer the generated files to be hosted.

It is a little painful right now to make any documentation updates right now with the wiki locked down and these PR's still being reviewed.  I'm hoping to have them hosted by next week some time, 2 weeks at the most.

**Comment by shaundmorris** [comment]
This is good stuff to discuss: let's move to the developers group https://groups.google.com/forum/?fromgroups#!topic/ddf-developers/L0DrCLAN-qM

**Pull request merged**
