### PR TITLE
DDF-1079: In the Catalog Federation Strategy dialog, it is necessary to disable ca...

### PR DESCRIPTION
**Pull request by btburns**
...ching of products as a workaround to the problem described in https://tools.codice.org/jira/browse/DDF-1029.

This solution involves reverting to the following changes:
https://github.com/codice/ddf-catalog/commit/873f7c74520fc097bf764a1e9554046de8904b71

In addition, more logic is required in the CachingFederationStrategy.java to guard against adding of records to the metacard cache when caching is disabled.

The ddf-ui SearchController.java class will also require an update to expect all results from a single 'index' mode in lieu of separately querying a 'cache' mode. When caching is enabled, all results are returned when querying 'index' mode.

These changes were tested using by reproducing the issue documented in DDF-1029 with caching enabled, and disabled. When disabled the problem documented in the DDF-1029 was not reproduced, but when enabled the problem was reproduced. The ability to use the existing catalog interfaces were also tested with caching enabled and disabled to ensure that the changes to the CachingFederationStrategy didn't introduce any errors.

### CODE REVIEW

**Comment by pklinef** [comment]
The bug in DDF-1079 was related to the remove commands doing a query with a default mode which caused the results to be recached after the delete.  This issue was fixed in the following commit.

https://github.com/codice/ddf-catalog/commit/fe9da3834cbec0754ad04638d9eff7533c2add99

**Comment by mrmateo** [comment]
@btburns - can you verify that fix @pklinef mentioned solves what you were doing?

**Comment by shaundmorris** [comment]
Of note the commit referenced is in master and the PR is for the 2.6.x branch. So @pklinef  should it be cherry-picked?

**Comment by btburns** [comment]
I cherry-picked his changes to my 2.6.x, and will test it to see if it does resolve the issue described in DDF-1029.

**Comment by btburns** [comment]
I just retested the changes on the 2.6.x branch, and I still see the problem documented in DDF-1029. Can we reopen this pull request?

**Comment by pklinef** [comment]
See https://github.com/codice/ddf-ui/pull/48#issuecomment-76745992

Please test again without using the -p flag.  It should fix the issue.

**Comment by btburns** [comment]
@pklinef - I tested w/o the -p option. Looks like caching is working fine. See: https://github.com/codice/ddf-ui/pull/48#issuecomment-76430673

**Comment by menousek** [comment]
@btburns based on your last comment can we close this request?

**Comment by btburns** [comment]
@menousek - this pull request is related to DDF-1079 - and actually disables the caching.

**Comment by btburns** [comment]
@pklinef - I updated the solution to retain the cache mode query, which will be evaluated when caching is enabled.

**Comment by pklinef** [comment]
@btburns Can you rebase your PR and force push it?  I am seeing other people's commits in your PR.  Also make sure all of your commits include the ticket number.

**Pull request closed without merging**
