### PR TITLE
DDF-1270: enabled compiling docs into single html/pdf file.

### PR DESCRIPTION
**Pull request by ricklarsen**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/104)

### CODE REVIEW

**Comment by clockard** [comment]
Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/104)

**Comment by clockard** [comment]
Reviewed 2 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/104)

**Comment by clockard** [comment]
:+1:

**Comment by ricklarsen** [comment]
@shaundmorris This PR is now ready to be reviewed.

**Pull request merged**
