### PR TITLE
DDF-1259 - added support for Insert via CSW Endpoint

### PR DESCRIPTION
**Pull request by kcwire**
@jlcsmith @millerw8 @wmcnalli @pklinef @jrnorth @kguerriero @beyelerb @shane-voisard @emanns95

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/128)

### CODE REVIEW

**Comment by kcwire** [comment]
@emanns95 is the hero.

**Comment by ricklarsen** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/128)

**Comment by emanns95** [comment]
Successfully built with tests

**Comment by kguerriero** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/128)

**Comment by kcwire** [comment]
@emanns95 that unit test failure should be fixed by DDF-1353.

**Comment by emanns95** [comment]
@kcwire I'm about to try building it again once my build finishes...okay it finished as I was typing this

**Comment by emanns95** [comment]
Build successful with tests this time!

**Comment by emanns95** [comment]
+1

**Comment by jrnorth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, line 131 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/128#-Jv-rOhQK2C9zWVOAlL_)** ([raw file](https://github.com/codice/ddf-catalog/blob/385069d9ec482d74258335a6ead27aab5c2bcb74/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L131)):</sup>
Is there a reason for this comment?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/128)

**Comment by kcwire** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, line 131 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/128#-Jv-rOhQK2C9zWVOAlL_)** ([raw file](https://github.com/codice/ddf-catalog/blob/385069d9ec482d74258335a6ead27aab5c2bcb74/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L131)):</sup>
removed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/128)

**Pull request merged**
