### PR TITLE
DDF-1342 Missing .gitignore value from the ddf-ui merge into catalog.

### PR DESCRIPTION
**Pull request by coyotesqrl**
Big change, I know.

@pklinef 
@tbatieConnexta 
@jckilmer
@rzwiefel
@roelens8

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/121)

### CODE REVIEW

**Comment by rzwiefel** [comment]
:+1:

**Comment by pklinef** [comment]
Ideally the styles.css file would be generated in the target folder instead of in the src directory.

**Comment by coyotesqrl** [comment]
I agree. However, I don't even know what process is generating those css files.

I can write up a ticket to address that, however.

**Comment by tbatieConnexta** [comment]
:+1:

**Comment by pklinef** [comment]
Ok, write a ticket and mention to remove that line from .gitignore once it is fixed.

:+1:

**Pull request merged**
