### PR TITLE
Hotfix/ddf 1209

### PR DESCRIPTION
**Pull request by brendan-hofmann**
88e11fb and up are new in this PR, the others are cherry-picked from master.

63efeb7 and up should be cherry-picked to master when this PR is approved.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/90)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
@pklinef @shaundmorris I'm still testing, but I wanted to leave as much time for feedback as possible.

**Comment by pklinef** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.
Reviewed files:
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluator.java @ r1
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualTokenizer.java @ r1
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java @ r2
- core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java @ r2

---

<sup>**[core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualTokenizer.java, line 41 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqpbL5urSC649_ufLmX)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualTokenizer.java#L41)):</sup>
Set<Character> on left.  HashSet<> on right for master.

---

<sup>**[core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java, line 152 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqpcWvCPEhNEysLF-At)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java#L152)):</sup>
Can you rename aChar and bChar to be clearer what they hold?

---

<sup>**[core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java, line 155 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqpctxSeg222evBAJrl)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java#L155)):</sup>
You can probably make this char and set it to \0.

---

<sup>**[core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java, line 1129 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqpeJ1CqK2n0DZ2Xp5q)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java#L1129)):</sup>
aChar again

---

<sup>**[core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java, line 1146 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqpedzOl50nxG1jh5eb)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java#L1146)):</sup>
aChar and bChar

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/90)

**Comment by shaundmorris** [comment]
Review status: 2 of 4 files reviewed, 3 unresolved discussions, some commit checks pending.
Reviewed files:
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluator.java @ r1
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualTokenizer.java @ r1
- core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java @ r2
- core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java @ r2

---

<sup>**[core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java, line 103 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-catalog/90#-JqplXHBNLmedFsOMqtK)** ([raw file](https://github.com/codice/ddf-catalog/blob/80fd3123baf0adac8973e309e551719141c04eb6/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContextualPredicate.java#L103)):</sup>
Like the use of StringBuilder for the concatenation. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/90)

**Comment by shaundmorris** [comment]
Built fine for me :+1:

**Comment by pklinef** [comment]
:+1:

**Pull request merged**
