### PR TITLE
DDF-1192: Updated restlet to version 2.1.4 and Xalan to version 2.7.2 to address other high severity vulnerabilities.

### PR DESCRIPTION
**Pull request by lessarderic**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/84)

### CODE REVIEW

**Comment by lessarderic** [comment]
@shaundmorris, @brendan-hofmann

**Comment by brendan-hofmann** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[pom.xml, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/84#-Jpm9Q731-JznnjX1n_m)** ([raw file](https://github.com/codice/ddf-catalog/blob/4c296f554a4012c30c28c4c2cab72dcd6a8fb93f/pom.xml#L49)):</sup>
I recommend referencing a ticket to update Solr in these comments, so that readers can easily determine if this workaround still needs to be here or not. Said ticket should also reference these workarounds so we don't forget to remove them.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/84)

**Comment by lessarderic** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[pom.xml, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-catalog/84#-Jpm9Q731-JznnjX1n_m)** ([raw file](https://github.com/codice/ddf-catalog/blob/4c296f554a4012c30c28c4c2cab72dcd6a8fb93f/pom.xml#L49)):</sup>
Good point. Create sub-task DDF-1203 and added reference in comments.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/84)

**Comment by shaundmorris** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- pom.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/84)

**Comment by brendan-hofmann** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- pom.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/84)

**Pull request merged**
