### PR TITLE
DDF-1074 moved mbean interface out of impl package

### PR DESCRIPTION
**Pull request by wmcnalli**
@pklinef 
@kcwire 
@jlcsmith 
@jrnorth

Clean up for a previously merged PR

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/112)

### CODE REVIEW

**Comment by kcwire** [comment]
:+1:

**Comment by pklinef** [comment]
:+1:

**Comment by wmcnalli** [comment]
@jlcsmith - can you hero this real quick?

**Comment by jlcsmith** [comment]
Looks good to me

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/112)

**Pull request merged**
