### PR TITLE
DDF-1018 Added a checkbox to the backup plugin to enable/disable, and se...

### PR DESCRIPTION
**Pull request by jvettraino**
...t it to disable by default.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/55)

### CODE REVIEW

**Comment by shaundmorris** [comment]
If there are no objections. I will merge this today since it is has been open for a few days

**Comment by stustison** [comment]
It looks like this is using an incorrect formatter.

**Comment by shaundmorris** [comment]
@jvettraino  I thought you mentioned you may have had some default formatter issues. Can you please take a look?

**Comment by jvettraino** [comment]
I used the ddf-eclipse formatter (same one I have been using for some time, that is on the wiki).  It hasn't updated since 2013.

Suggestions?

**Comment by kcwire** [comment]
Sorry late to the conversation but why are we disabling this by default?

**Comment by shaundmorris** [comment]
After looking at the file it looks like it was committed with the incorrect format. Specifically things like "for(" and "if(" should be "for (" and "if ("

**Comment by shaundmorris** [comment]
@kcwire Good question. I think the main goal was to make it a checkbox. Overall I think this and items like it will get addressed with refactoring the Active/Inactive status for applications. I don't have a strong preference on the default. I'm assuming the case for default to true is for reliability/failover. False may gain some performance. I will merge in, reformat, and change the default to true. @kcwire or @stustison  feel free to ping me if I need to make any additional changes.

**Pull request merged**
