### PR TITLE
DDF-1347: Corrected exception handling on federated search

### PR DESCRIPTION
**Pull request by jlcsmith**
@millerw8 @kcwire @wmcnalli @beyelerb @emanns95 @coyotesqrl

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/124)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/124)

**Comment by kcwire** [comment]
:+1:

**Comment by emanns95** [comment]
+1

**Comment by jlcsmith** [comment]
@kcwire - this should be ready to go pending the bamboo build

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/124)

**Pull request merged**
