### PR TITLE
DDF-1307 fixes missing bundle dependencies; removes orphaned module

### PR DESCRIPTION
**Pull request by coyotesqrl**
If the order of bundle loading occurred in the correct magic sequence, `catalog-transformer-xml` would load correctly. This fixes the bundle dependencies directly.

I think this list of reviewers should get us resolved quickly.

Travis, would you please be the hero on this?

@pklinef 
@stustison 
@brendan-hofmann 
@mverret 
@AzGoalie

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/106)

### CODE REVIEW

**Comment by pklinef** [comment]
:+1:

**Comment by AzGoalie** [comment]
Built and tests passed
:+1:

**Comment by brendan-hofmann** [comment]
Looks right to me. :+1:

**Comment by brendan-hofmann** [comment]
:+1:

**Comment by coyotesqrl** [comment]
@AzGoalie should this be merged?

**Pull request merged**
