### PR TITLE
DDF-439 added solr:backup command to make backups of solr cores from …

### PR DESCRIPTION
**Pull request by jaymcnallie**
…the karaf console
@kcwire 
@jlcsmith 
@millerw8 
@beyelerb 
@jrnorth 
@kguerriero
@emanns95

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-catalog/135)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
No more PRs are coming in from ddf-catalog; we've begun the repo merge process. Hopefully it'll all be merged by midday tomorrow, at which time you'll have to recreate this against ddf.

**Comment by jaymcnallie** [comment]
@coyotesqrl got it!  just wanted to get this under review.  i'll open another tomorrow on the merged repo.

**Comment by jaymcnallie** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 109 [r1]](https://reviewable.io:443/reviews/codice/ddf-catalog/135#-Jvy4Rfrk5gkf-jFTDQP)** ([raw file](https://github.com/codice/ddf-catalog/blob/acf9fc3692b9f9d80188cd9b040a7af89a0a825e/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L109)):</sup>
Not sure if this assumption is correct.  Thinking I should pull in the solr config and parse the hostname out of the external Solr provider url.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/135)

**Comment by jaymcnallie** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 109 [r1]](https://reviewable.io:443/reviews/codice/ddf-catalog/135#-Jvy4Rfrk5gkf-jFTDQP)** ([raw file](https://github.com/codice/ddf-catalog/blob/acf9fc3692b9f9d80188cd9b040a7af89a0a825e/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L109)):</sup>
https://codice.atlassian.net/browse/DDF-1387 opened to fix.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-catalog/135)

**Pull request closed without merging**
